version: '3.8'
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
  app:
    depends_on:
      - db
    build:
      context: .
    restart: unless-stopped
    env_file: .env
    ports:
      - $SERVER_PORT:$SERVER_PORT
    environment:
      - SERVER_PORT=$SERVER_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - DB_HOST=db
    tty: true